codecov:
  notify:
    after_n_builds: 1

comment:
  layout: 'reach, diff, flags, files' # What appears in the comment
  behavior: default # Sempre comments no PR
  require_changes: false # Shows comment even without change of coverag
  branches: ['main', 'develop']

coverage:
  status:
    project:
      default:
        enabled: true
        target: auto
    patch:
      default:
        enabled: true
        target: auto
