name: CI

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        include:
          - branch: main
            artifact: main
          - branch: ${{ github.head_ref }}
            artifact: pull-request

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          ## Set repository to correctly checkout from forks
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }} # Adding the token

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format

      - name: Run tests with coverage
        run: npm run test

      - name: 'Upload Coverage'
        if: env.ACT != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-pull-request
          path: coverage

      - name: Build
        run: npm run build

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Download Coverage Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: coverage-pull-request # Apenas baixe o coverage para o pull request
          path: coverage
      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage/coverage-summary.json
